"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "local-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "log_analyzer",
    "rest_framework.authtoken",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



if os.environ.get("DJANGO_ENV") == "production":
    DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ["POSTGRES_DB"],
                "USER": os.environ["POSTGRES_USER"],
                "PASSWORD": os.environ["POSTGRES_PASSWORD"],
                "HOST": os.environ["POSTGRES_HOST"],
                "PORT": os.environ.get("POSTGRES_PORT", "5432"),
                "CONN_MAX_AGE": 60,
                "CONN_HEALTH_CHECKS": True,
                "OPTIONS": {
                    "sslmode": "require",
                    "connect_timeout": 10,
                },
            }
        }
else:

    DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "data" / "db.sqlite3",
    }
}


# DATABASES = {
# "default": {
#     "ENGINE": "django.db.backends.sqlite3",
#     "NAME": BASE_DIR / "data" / "db.sqlite3",
# }}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Paths and addresses are supplied by Docker Compose in containers.
HDFS_TEMPLATE_PATH = Path(os.environ.get(
    "HDFS_TEMPLATE_PATH",
    str(BASE_DIR.parent / "HDFS_v1 (1)" / "preprocessed" / "HDFS.log_templates.csv"),
))
HDFS_MODEL_PATH = Path(os.environ.get(
    "HDFS_MODEL_PATH",
    str(BASE_DIR.parent / "outputs" / "anomaly_model.joblib"),
))
HDFS_ALLOWED_LOG_URLS = os.environ.get(
    "HDFS_ALLOWED_LOG_URLS",
    "http://127.0.0.1:9000/sample_hdfs.log,http://127.0.0.1:9000/HDFS.log",
).split(",")



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

HDFS_ALLOWED_LOG_URLS = [
    "http://host.docker.internal:9005/HDFS.log",
]



import os

ELASTICSEARCH_URL = os.getenv(
    "ELASTICSEARCH_URL",
    "http://localhost:9200",
)
ELASTICSEARCH_API_KEY = os.getenv("ELASTICSEARCH_API_KEY")
ELASTICSEARCH_PREDICTION_INDEX = "block-predictions"



KAFKA_BOOTSTRAP_SERVERS = os.environ.get("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")
KAFKA_JOB_TOPIC = os.environ.get("KAFKA_JOB_TOPIC", "log-jobs")
KAFKA_CONSUMER_GROUP = os.environ.get("KAFKA_CONSUMER_GROUP", "hdfs-job-processors")
KAFKA_PREDICTION_TOPIC = os.environ.get("KAFKA_PREDICTION_TOPIC", "prediction-jobs")
KAFKA_PREDICTION_GROUP = os.environ.get("KAFKA_PREDICTION_GROUP", "hdfs-prediction-processors")
LOG_PARSE_WORKERS = int(os.environ.get("LOG_PARSE_WORKERS", "10"))
LOG_CHUNK_SIZE = int(os.environ.get("LOG_CHUNK_SIZE", "200000"))
LOG_FEATURE_BATCH_SIZE = int(os.environ.get("LOG_FEATURE_BATCH_SIZE", "100000"))
LOG_PREDICTION_BATCH_SIZE = int(os.environ.get("LOG_PREDICTION_BATCH_SIZE", "100000"))
STATIC_ROOT = BASE_DIR / "staticfiles"





KAFKA_EVALUATION_TOPIC = os.getenv("KAFKA_EVALUATION_TOPIC", "evaluation-jobs")
KAFKA_EVALUATION_GROUP = os.getenv("KAFKA_EVALUATION_GROUP", "hdfs-evaluation-processors")
HDFS_LABEL_PATH = os.getenv("HDFS_LABEL_PATH", "/outputs/anomaly_label.csv")