# Generated by Django 5.2.17 on 2026-10-02 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=100)),
                ('event_counts', models.JSONField(default=dict)),
                ('feature_vector', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='LogJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('converted', 'Converted'), ('predicting', 'Predicting'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('event_ids', models.JSONField(default=list)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('statistics', models.JSONField(default=dict)),
                ('total_blocks', models.PositiveBigIntegerField(default=0)),
                ('normal_count', models.PositiveBigIntegerField(default=0)),
                ('anomaly_count', models.PositiveBigIntegerField(default=0)),
                ('expected_chunks', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_lines', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Normal', 'Normal'), ('Anomaly', 'Anomaly')], max_length=7)),
                ('anomaly_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='log_analyzer.blockfeature')),
            ],
        ),
        migrations.AddField(
            model_name='blockfeature',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='log_analyzer.logjob'),
        ),
        migrations.CreateModel(
            name='LogChunkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.PositiveIntegerField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('block_counts', models.JSONField(default=dict)),
                ('statistics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_results', to='log_analyzer.logjob')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'chunk_id'), name='unique_chunk_result_per_job')],
            },
        ),
        migrations.AddConstraint(
            model_name='blockfeature',
            constraint=models.UniqueConstraint(fields=('job', 'block_id'), name='unique_block_per_log_job'),
        ),
    ]
